#!/bin/bash

INSTANCE=$(screen -li | grep kibana | sed 's/\s/ /g')

if [ -n "$INSTANCE" ]
then
    echo "Already running: $INSTANCE"
else
    mkdir -p /vagrant/logs

    screen -S kibana -d -m bash -l -c "su - vagrant -c \"kibana serve > /vagrant/logs/kibana-$VM_NAME.log 2>&1\""
    echo "-----------------------------------------------------------------------------------------------------------"
    echo " => Started $VM_NAME - $VM_NODE_NAME - $VM_NODE_IP: $(screen -li | grep kibana | sed 's/\s/ /g')"
    echo "-----------------------------------------------------------------------------------------------------------"
fi
