#!/bin/bash

INSTANCE=$(screen -li | grep logstash | sed 's/\s/ /g')

if [ -n "$INSTANCE" ]
then
    echo "Already running: $INSTANCE"
else
    mkdir -p /vagrant/logs

    screen -S logstash -d -m bash -l -c "su - vagrant -c \"LS_JAVA_OPTS='-Djava.net.preferIPv4Stack=true' logstash -f /vagrant/conf/logstash-${VM_NAME}.conf > /vagrant/logs/logstash-${VM_NAME}.log 2>&1\""
    echo "-----------------------------------------------------------------------------------------------------------"
    echo " => Started $VM_NAME - $VM_NODE_NAME - $VM_NODE_IP: $(screen -li | grep logstash | sed 's/\s/ /g')"
    echo "-----------------------------------------------------------------------------------------------------------"
fi
